# name of CI/CD pipeline
name: CI/CD Pipeline

permissions:
  security-events: write

# Specifies when the pipeline should run.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ (matrix.language == 'csharp' && 'windows-latest') || 'ubuntu-latest' }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
 
    - name: Install .NET MAUI workload
      run: |
        dotnet workload install maui
        dotnet workload install maui-android
        dotnet workload install maui-ios
        dotnet workload install maccatalyst

    - name: Build Application
      run: |
        dotnet restore
        dotnet build --no-restore


    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    #- name: Install MAUI workloads
     # run: |
      #  dotnet workload install maui
       # dotnet workload install maui-android
        #dotnet workload install maui-ios
        #dotnet workload install maccatalyst

  #  - name: Initialize CodeQL
  #    uses: github/codeql-action/init@v2
  #    with:
  #      languages: 'csharp'

  #  - name: Perform CodeQL Analysis
  #    uses: github/codeql-action/analyze@v2

  build_and_test:
    needs: analyze
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-android
        dotnet workload install maui-ios
        dotnet workload install maccatalyst

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --framework net6.0-windows

  deploy_to_staging:
    needs: build_and_test
    if: github.ref != 'refs/heads/main' && github.event_name == 'push'
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Deploy to Azure Web App (Staging)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TaskMasterService'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
        package: './'

  deploy_to_production:
    needs: build_and_test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TaskMasterApp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './'
